#!/usr/bin/env python3
"""Generate the wiki's derived layer: index.md and per-page backlinks.

Rule this script exists to enforce: anything that can be computed from the
pages must not be maintained by hand. Hand-written derived data is what turns
one ingest into eight file edits and lets the index drift from reality.

Source of truth
  - a page's frontmatter (title, type, summary)  -> its line in index.md
  - a page's outbound [[wiki/...]] links          -> everyone else's backlinks

Blast radius (deliberately small): this script rewrites index.md and the
region between the backlink markers on each wiki page. It never touches
frontmatter, prose, sources/, or log.md.

Usage
  scripts/derive.py           regenerate derived artifacts in place
  scripts/derive.py --check   exit 1 if anything is out of date (CI / lint)
"""

from __future__ import annotations

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
WIKI = ROOT / "wiki"
INDEX = ROOT / "index.md"

BL_START = "<!-- backlinks:start (generated by scripts/derive.py — do not edit by hand) -->"
BL_END = "<!-- backlinks:end -->"
BL_BLOCK = re.compile(
    re.escape(BL_START) + r".*?" + re.escape(BL_END), re.DOTALL
)
LINK = re.compile(r"\[\[wiki/([a-z0-9-]+)\]\]")

# Routing is domain-first: a question belongs to a domain before it belongs to
# a page type. `thinking` is the core domain every other one draws on — see
# wiki/domain-map.md. Domains with no pages yet are listed so the shape of the
# brain is visible even where it is still empty.
DOMAINS = [
    ("thinking", "Thinking (tư duy) — the core domain"),
    ("agents", "Agent systems"),
    ("programming", "Programming craft (chuyên môn)"),
    ("psychology", "Psychology & emotion (cảm xúc)"),
    ("economics", "Economics (kinh tế)"),
    ("brain", "This brain itself (meta)"),
]

# Within a domain, pages are grouped by their frontmatter `type`.
SECTIONS = [
    ("meta", "Meta"),
    ("concept", "Concepts"),
    ("entity", "Entities"),
    ("synthesis", "Syntheses"),
    ("summary", "Source summaries"),
]

INDEX_HEADER = """# Index

Catalog of every wiki page, one line each — grouped by **domain** first, then by
page type. This is the *navigation layer*: route a question to its domain, then
to the few relevant pages, rather than loading the whole vault.

The domain list is fixed and shows empty domains too, so what is missing stays
as visible as what exists. See [[wiki/domain-map]] for how the domains relate.

<!-- GENERATED by scripts/derive.py from each page's frontmatter (title, type,
     domain, summary). Do not edit by hand — edit the page's frontmatter and
     re-run `scripts/derive.py`. -->
"""


def parse_frontmatter(text: str) -> dict[str, str]:
    """Minimal frontmatter reader — no pyyaml, so CI needs no extra install."""
    if not text.startswith("---\n"):
        return {}
    end = text.find("\n---", 3)
    if end == -1:
        return {}
    out: dict[str, str] = {}
    for line in text[4:end].splitlines():
        if not line.strip() or line.lstrip().startswith("#") or ":" not in line:
            continue
        key, _, value = line.partition(":")
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1].replace('\\"', '"')
        out[key.strip()] = value
    return out


def split_body(text: str) -> tuple[str, str]:
    """Return (frontmatter-with-delimiters, body). Body is everything after."""
    if text.startswith("---\n"):
        end = text.find("\n---", 3)
        if end != -1:
            cut = end + len("\n---")
            nl = text.find("\n", cut)
            if nl != -1:
                return text[: nl + 1], text[nl + 1 :]
    return "", text


def load_pages() -> dict[str, dict]:
    pages: dict[str, dict] = {}
    for path in sorted(WIKI.glob("*.md")):
        text = path.read_text(encoding="utf-8")
        fm, body = split_body(text)
        pages[path.stem] = {
            "path": path,
            "text": text,
            "fm_raw": fm,
            "body": body,
            "meta": parse_frontmatter(text),
        }
    return pages


def outbound(body: str) -> set[str]:
    """Links a page genuinely makes — the generated block is excluded so
    backlinks can never bootstrap themselves into existence."""
    return set(LINK.findall(BL_BLOCK.sub("", body)))


def render_index(pages: dict[str, dict]) -> str:
    grouped: dict[tuple[str, str], list[tuple[str, str, str]]] = {}
    for slug, page in pages.items():
        meta = page["meta"]
        key = (meta.get("domain", "thinking"), meta.get("type", "concept"))
        grouped.setdefault(key, []).append(
            (meta.get("created", "0000-00-00"), meta.get("title", slug), slug)
        )

    known_domains = {d for d, _ in DOMAINS}
    known_types = {t for t, _ in SECTIONS}
    for domain, type_key in grouped:
        if domain not in known_domains:
            raise SystemExit(
                f"derive: unknown domain '{domain}' — add it to DOMAINS in "
                f"scripts/derive.py or fix the page's frontmatter"
            )
        if type_key not in known_types:
            raise SystemExit(
                f"derive: unknown page type '{type_key}' — add a section in "
                f"scripts/derive.py or fix the page's frontmatter"
            )

    out = [INDEX_HEADER]
    for domain, domain_label in DOMAINS:
        out.append(f"\n## {domain_label}\n")
        if not any(d == domain for d, _ in grouped):
            out.append("\n*No pages yet.*\n")
            continue
        for type_key, type_label in SECTIONS:
            entries = sorted(grouped.get((domain, type_key), []))
            if not entries:
                continue
            out.append(f"\n### {type_label}\n")
            for _created, _title, slug in entries:
                summary = pages[slug]["meta"].get("summary", "").strip()
                out.append(f"- [[wiki/{slug}]] — {summary}\n" if summary
                           else f"- [[wiki/{slug}]]\n")
    return "".join(out)


def render_backlinks(slug: str, inbound: dict[str, set[str]]) -> str:
    linkers = sorted(inbound.get(slug, ()))
    if linkers:
        listed = " · ".join(f"[[wiki/{s}]]" for s in linkers)
    else:
        listed = "_nothing links here yet — this page is an orphan_"
    return f"{BL_START}\n\n---\n\n**Linked from:** {listed}\n{BL_END}\n"


def apply_backlinks(pages: dict[str, dict]) -> dict[pathlib.Path, str]:
    inbound: dict[str, set[str]] = {slug: set() for slug in pages}
    for slug, page in pages.items():
        for target in outbound(page["body"]):
            if target in inbound and target != slug:
                inbound[target].add(slug)

    wanted: dict[pathlib.Path, str] = {}
    for slug, page in pages.items():
        body = BL_BLOCK.sub("", page["body"]).rstrip() + "\n"
        wanted[page["path"]] = page["fm_raw"] + body + "\n" + render_backlinks(slug, inbound)
    return wanted


def main() -> int:
    check = "--check" in sys.argv[1:]
    pages = load_pages()
    if not pages:
        print("derive: no wiki pages found", file=sys.stderr)
        return 1

    wanted = apply_backlinks(pages)
    wanted[INDEX] = render_index(pages)

    stale = []
    for path, content in sorted(wanted.items()):
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        stale.append(path.relative_to(ROOT))
        if not check:
            path.write_text(content, encoding="utf-8")

    if check:
        if stale:
            print("  ✗ derived files are out of date — run scripts/derive.py:")
            for path in stale:
                print(f"      {path}")
            return 1
        print("  ✓ derived files up to date")
        return 0

    if stale:
        print(f"derive: rewrote {len(stale)} file(s)")
        for path in stale:
            print(f"  {path}")
    else:
        print("derive: everything already up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
